### ISSUE TITLE
question: public domain licences and copyright-holder `none`

### ISSUE THREAD

**Issue by david-fong** [fsfe/reuse-docs#109]
## background

[The tutorial recommends this](https://reuse.software/tutorial/#insignificant-files):

> ```
> # SPDX-FileCopyrightText: 2019 Jane Doe <jane@example.com>
> #
> # SPDX-License-Identifier: CC0-1.0
> ```

[THE KDE guidelines say this](https://community.kde.org/Guidelines_and_HOWTOs/Licensing#Which_copyright_holder_shall_I_add_to_a_CC0-1.0_file?):

> For a non-copyrightable file there cannot be a copyright holder. However, the REUSE project expects to make a conscious decision about it. It is absolutely when when you just add a SPDX-FileCopyrightText statement that tells, nobody has copyright on this file, e.g.:
>
> ```
> SPDX-FileCopyrightText: none
> SPDX-License-Identifier: CC0-1.0
> ```

[a quote from another issue thread in this repo](https://github.com/fsfe/reuse-docs/issues/62#issuecomment-625813003):

> we could also allow NONE which just was enabled by the latest SPDX release. But well, that's not really what REUSE wants to procure...

## questions

1. why doesn't REUSE want to recommend `SPDX-FileCopyrightText: none` for public domain code?
2. Is the quoted KDE statement wrong (the first sentence)? Why or why not?

**Comment by carmenbianca** [comment]
1. @mxmehl 's comment related to `SPDX-License-Identifier`, not `SPDX-FileCopyrightText`. It's fine to write 'none' as the copyright holder if that accurately represents reality.
2. 'For a non-copyrightable file there cannot be a copyright holder' is tricky because who determines the threshold of copyrightability? In any case, the REUSE spec mandates that you write down _something_ behind `SPDX-FileCopyrightText`.

**Comment by david-fong** [comment]
Thanks! I'll wait a week if that's okay to see if anyone else wants to chime in before closing this github issue.

**Comment by david-fong** [comment]
Here's a follow-up question: would it be wrong to put my name in the `SPDX-FileCopyrightText` for a machine-generated package-lock file instead of putting `none`?

**Comment by carmenbianca** [comment]
There's no real harm in doing that. Let's imagine two scenarios for a moment.

First scenario:

- You generate a package-lock file and mark it as `SPDX-FileCopyrightText: David Fong` and `SPDX-License-Identifier: GPL-3.0-or-later`.
- Someone else (let's call them Alice) wants to re-use this file in non-GPL project.
- Alice asserts that your copyright header is completely incorrect. She thinks that this file cannot be copyrighted, and that she is therefore free to copy it.
- Alice copies the file and changes the header to `SPDX-FileCopyrightText: None` and `SPDX-License-Identifier: CC0-1.0`.
- You see what Alice has done. You can then do the following things:
  - Nothing.
  - Agree with Alice and change the header yourself.
  - Sue Alice and lose in court because her assessment was probably correct. You probably won't do this.

No harm done. At worst, you were unhelpful to Alice, and she had to exert extra effort to analyse the licensing and change the header.

Second scenario:

- You generate a package-lock file and mark it as `SPDX-FileCopyrightText: David Fong` and `SPDX-License-Identifier: CC0-1.0`.
- Someone else (Bob this time) wants to re-use this file.
- Bob likes the following things about the licensing of the file:
  - It's clearly marked CC0-1.0. This means he can use it for whatever.
  - The source of the file is implied through the `SPDX-FileCopyrightText` tag. This gives Bob confidence that the CC0-1.0 licence was correctly applied by that source.
- Bob dislikes the following things about the licensing of the file:
  - Like Alice, Bob asserts that the file is not copyrightable. Therefore, you being the 'copyright holder' doesn't make much sense, because there _is_ no copyright holder. Furthermore, Bob could assert that uncopyrightable files can't have licences either, [but this is a known limitation of REUSE](https://github.com/fsfe/reuse-docs/issues/62).
- Bob can do two things:
  - Just copy the file as-is. This is the easiest thing to do, and it really doesn't matter that much, because the licence is CC0-1.0 anyway.
  - Change the header to `SPDX-FileCopyrightText: None`. If Bob does this, you probably don't care, because you slapped the CC0-1.0 licence on the file. If you wanted attribution, you would have chosen a different licence. You have—as far as I can tell—no legal recourse to force Bob to put your name back in the header.

Effectively zero harm done.

**Comment by david-fong** [comment]
Thanks so much for the thorough answer! That was very helpful :)
