### ISSUE TITLE
Screenshot of copyrighted media

### ISSUE THREAD

**Issue by maddovr** [fsfe/reuse-docs#119]
Hello, I want to make my website compliant to the reuse spec. For posts and source code of said website (which is a static one) there is no problem but I'm left wondering about what to do with media files. I've read the spec, however in my website I sometime talk about copyrighted content (like movies/tv series/anime) and post a few screenshots on my website from said content to perhaps point out quality defects in the video or in the subtitles. Those screenshots fall under the fair use of copyrighted material (for review purposes) but I'm unsure which license/indicator is the appropriate one per SPDX specification. I've found the https://spdx.org/licenses/Fair but it doesn't seem like it's the right one. May I have some delucidations about this?

**Comment by silverhook** [comment]
Copy-pasting my answer to the same question on [REUSE mailing list](https://lists.fsfe.org/pipermail/reuse/2023q1/000159.html):

Just a quick (not entirely) answer.

There is no “fair use” SPDX ID because “fair use” is not a license, it’s an 
statutory exception/defense in court, so technically no license is needed. 
Also do note that “fair use” is USA specific; UK has “fair dealings” and in 
continental Europe the exception you are looking for will most likely be 
“critique” and/or “citation”.

That said, it is a good question.

Perhaps checking how Wikipedia handles this, could be a good start as 
inspiration:
https://en.wikipedia.org/wiki/Wikipedia:Non-free_content

And from there you could create a custom SPDX ID for each picture explaining 
why you think it’s OK for you to use it according to the law and to properly 
quote it (e.g. `LicenseRef-picture_Movie1_Shot2`).

Very much looking forward for others’ thoughts.

**Comment by carmenbianca** [comment]
I would also do something like `LicenseRef-FairUse` with a small text describing what you're doing.

**Comment by mxmehl** [comment]
There was no follow-up here or on the list so I'll close this issue.
