### ISSUE TITLE
COPYING and LICENSE are ignored by the tool; this is not mentioned in the spec

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-docs#139]
Raised in https://github.com/fsfe/reuse-tool/issues/881#issuecomment-1862780188

**Comment by carmenbianca** [comment]
#133 might fix this

**Comment by silverhook** [comment]
Should the tool or the spec be the original source of truth?

TBH, I’d prefer the spec to be clean and the tool to adapt. With `reuse.toml` it should be trivial to ignore the `COPYING` and `LICENSE` files if they exist.

The reason why `LICENSES/` is ignored in the spec is because it is _part of_ the spec. Ignoring files and folders that are not part of the spec is tricky, because their naming and actual use is outside of our control. (e.g. there’s `LICENSE`, `LICENCE`, `COPYRIGHT`, `COPYING`, `LICENSE.GPL`, etc. etc.)

**Comment by carmenbianca** [comment]
Implemented in spec
