### ISSUE TITLE
Spec: Define what files go into `.reuse/`

### ISSUE THREAD

**Issue by carmenbianca** [fsfe/reuse-docs#29]
Thread: https://github.com/fsfe/reuse-docs/pull/23#discussion_r285259001

Gist of it is: If we flatly allow all files in `.reuse/` to be ignored by the linter, this opens vectors for abuse. (e.g., sneakily storing unlicensed code in there).

@silverhook @mxmehl @carmenbianca

**Comment by mxmehl** [comment]
I am not sure how realistic the sneaky scenario is. If someone sees need to prevent that, we can agree on a definition, or a name pattern and content description. Otherwise, I would keep it as general as possible like 

`The folder .reuse/ only contains files necessary for checking and ensuring REUSE compliance. Actual code or documentation must not be stored inside this folder.`

**Comment by carmenbianca** [comment]
I don't think anything needs to be changed here. There are a lot of vectors for abuse if you're looking for them. You could have a "./configure" script that downloads malware from the internet and puts it in "shady-directory", which is ignored by ".gitignore".

**Comment by silverhook** [comment]
Setting the backdoor argument aside, if `.reuse/` will include stuff that will have to be parsed by REUSE tools, that stuff will have to be defined as well.

I’m OK with setting this aside for a later revision, once we know what stuff we want/need in that folder.

**Comment by carmenbianca** [comment]
Added the REUSE 3.1 milestone for this.

**Comment by carmenbianca** [comment]
Fixed by c534c57
