### ISSUE TITLE
Recommendation for handling COPYING files for GPL/LGPL

### ISSUE THREAD

**Issue by cordlandwehr** [fsfe/reuse-docs#56]
The GPL howto explains that license users shall add a file called COPYING or COPYING.LESSER into the root of their projects (https://www.gnu.org/licenses/gpl-howto.html). I would argue that these files are obsolete, as the license files are already shipped inside the LICENSES/ directory when following the REUSE specification. 
Do you have an opinion on this topic? If yes, it would be great to see that opinion on the FAQ section.

**Comment by silverhook** [comment]
> I would argue that these files are obsolete, as the license files are already shipped inside the LICENSES/ directory when following the REUSE specification.

I would argue the same.

I would add though, that for those who really want/need to follow the GNU/FSF instructions by the letter, nothing prevents you from following both at the same time. Although doing so would produce two places where one might find licensing information and as such might introduce some ambiguity and confusion.

Personally, I would simply follow the REUSE spec and, if needed, use the `COPYING` file to summarise the licensing situation.

**Comment by carmenbianca** [comment]
This kind of seems like a fact of life to me. There are always going to be incompatibilities between standards, and REUSE explicitly chose to break new ground instead of attempting to be compatible with old tradition. There could be a FAQ item that asks "I'm using to doing things X way; can I still do that?". The answer could ellaborate on the fact that REUSE breaks tradition.

Of course, you can still do things the old way. But from REUSE's perspective, that would be completely unnecessary.

**Comment by mxmehl** [comment]
> There could be a FAQ item that asks "I'm used to doing things X way; can I still do that?". The answer could ellaborate on the fact that REUSE breaks tradition.

Good idea, could also be reaction to the same question with the LICENSE file. Shall we use this issue to track this?

> Personally, I would simply follow the REUSE spec and, if needed, use the COPYING file to summarise the licensing situation.

That's something I would like to propose to the REUSE mailing list soon. REUSE could come up with a standard text and some text fields how people can declare in a central LICENSE (or COPYRING) file that this is a REUSE compliant repo, where to find the license texts, and perhaps even define a desired inbound (and outbound?) license to suit the need of people who adore the concept of a "main license". This issue is not the right place to discuss that, just wanted to mention it.

**Comment by uiopaubo** [comment]
One annoying thing about replacing existing licence files with the copy installed in the LICENSES directory is that the SPDX-generated copy will not be identical to the canonical version of the licence, at least as far as the GPLv3 is concerned. This is due to the SPDX initiative generating new plain text versions from apparently separately-developed XML versions of the licences.

I filed a bug for that here: https://github.com/spdx/license-list-XML/issues/1076

There is also some separate discussion about these matters: https://github.com/spdx/license-list-data/issues/44
