### ISSUE TITLE
provide definition of "license"

### ISSUE THREAD

**Issue by zvr** [fsfe/reuse-docs#89]
The specification has as a cornerstone statement:

>A Project MUST include a License File for every _license_ under which files in the Project are licensed.
(emphasis added)

However, files are licensed under _License Expressions_, not single licenses.
For example, if a file is under `BSD-3-Clause AND GPL-2.0-or-later`, the desired outcome should be that there are files for each of the component parts `BSD-3-Clause.txt` and `GPL-2.0-or-later.txt` and not a single one.

Even more so if the expression is of the form `License WITH Exception`. 

Somehow this must be cleared up.

**Comment by silverhook** [comment]
I’m not sure it’s needed. Files are licensed under licenses (note the lack of capitalisation, so this is a common term, not a defined term within REUSE or SPDX specs). SPDX _License Expressions_ are just a very convenient way to unambiguously and in a short way express which licenses the files are licensed under.

That being said, if the wording causes confusion, it might make sense to clarify better. But since (IMHO) the current state works as intended, the change (again IMHO) should be a very clear improvement in clarity. Else it is better to keep it as is.

I’ll try to think of something today.

**Comment by zvr** [comment]
Yes, thanks!

**Comment by zvr** [comment]
I will not raise the "one license == one file" topic now ;-)

**Comment by silverhook** [comment]
Because it’s fixed, or because you’re kind to us? ;)
